server:
  port: 8082
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: transformed
        test-sink:
          destination: transformed
        input:
          destination: testtock
        test-source:
          destination: testtock
