spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams:
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  bindings.kstreamIn.consumer.application-id: kafka-streams-to-rabbitmq
spring.cloud.stream.bindings.kstreamIn:
  destination: words
spring.cloud.stream.bindings.kstreamOut:
    destination: counts
spring.cloud.stream.bindings.fromKafka:
  destination: counts
  binder: kafka
spring.cloud.stream.bindings.toRabbit:
  destination: countsInRabbit
  binder: rabbit

spring.cloud.stream.bindings.testInputFromRabbit:
  destination: countsInRabbit
  binder: rabbit

spring.cloud.stream.kafka.streams.binder:
  brokers: localhost
