spring.cloud.stream.bindings.output.contentType: application/json
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams:
  binder.configuration:
    key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  bindings.output.producer:
    keySerde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
    valueSerde: org.apache.kafka.common.serialization.Serdes$LongSerde
spring.cloud.stream.bindings.output:
  destination: product-counts
  producer:
    useNativeEncoding: true
spring.cloud.stream.bindings.input:
  destination: products
  consumer:
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost #192.168.99.100
spring.application.name: kafka-streams-iq-basic-sample
