spring.cloud.stream.bindings.singleOutput.contentType: application/json
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.singleOutput:
  destination: counts
  producer:
    headerMode: raw
    #useNativeEncoding: true
spring.cloud.stream.bindings.binding2:
  destination: words
  consumer:
    headerMode: raw
spring.cloud.stream.bindings.binding1:
  destination: words
  consumer:
    headerMode: raw
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost #192.168.99.100
  zkNodes: localhost #192.168.99.100



