spring:
  cloud:
    stream:
      bindings:
        output:
          destination: xformed
        test-sink:
          destination: xformed
        input:
          destination: testtock
        test-source:
          destination: testtock
