spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.output1:
  destination: english-counts
spring.cloud.stream.bindings.output2:
  destination: french-counts
spring.cloud.stream.bindings.output3:
  destination: spanish-counts
spring.cloud.stream.bindings.input:
  destination: words
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost #192.168.99.100 #localhost
spring.application.name: kafka-streams-branching-sample